"""empty message

Revision ID: 0d346c0bec2c
Revises: 5459e19e3980
Create Date: 2025-09-10 22:53:11.533412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d346c0bec2c'
down_revision = '5459e19e3980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('sobrenome', sa.String(length=100), nullable=False))
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('sobrenome')
        batch_op.drop_column('nome')

    # ### end Alembic commands ###
