"""empty message

Revision ID: 0daa63b3c865
Revises: 
Create Date: 2025-09-10 11:31:54.711204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0daa63b3c865'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('livro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('autor', sa.String(), nullable=True),
    sa.Column('editora', sa.String(), nullable=True),
    sa.Column('publicacao', sa.DateTime(), nullable=True),
    sa.Column('genero', sa.String(), nullable=True),
    sa.Column('numeroDisponiveis', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cadastro', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('sobrenome', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cadastro')
    )
    op.create_table('aluguel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_livro', sa.Integer(), nullable=True),
    sa.Column('id_aluno', sa.Integer(), nullable=True),
    sa.Column('data_aluguel', sa.DateTime(), nullable=True),
    sa.Column('data_devolucao', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_aluno'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['id_livro'], ['livro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aluguel')
    op.drop_table('user')
    op.drop_table('livro')
    op.drop_table('aluno')
    # ### end Alembic commands ###
