"""empty message

Revision ID: 0e638238c622
Revises: 0d346c0bec2c
Create Date: 2025-09-11 08:30:58.257277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e638238c622'
down_revision = '0d346c0bec2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluguel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emprestimo_ativo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluguel', schema=None) as batch_op:
        batch_op.drop_column('emprestimo_ativo')

    # ### end Alembic commands ###
