"""empty message

Revision ID: 5459e19e3980
Revises: 0daa63b3c865
Create Date: 2025-09-10 22:39:53.481453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5459e19e3980'
down_revision = '0daa63b3c865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ano_publicacao', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('exemplares', sa.Integer(), nullable=False))
        batch_op.alter_column('titulo',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('autor',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('editora',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('genero',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('publicacao')
        batch_op.drop_column('numeroDisponiveis')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numeroDisponiveis', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('publicacao', sa.DATETIME(), nullable=True))
        batch_op.alter_column('genero',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('editora',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('autor',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('titulo',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('exemplares')
        batch_op.drop_column('ano_publicacao')

    # ### end Alembic commands ###
